FROM openjdk:8-jdk

USER root

#####
# CodeOnTap Configuration
#####

# Directory set up and file copying 
RUN mkdir -p /build/scripts
RUN mkdir -p /opt/codeontap
RUN mkdir -p /var/opt/codeontap

COPY scripts/ /build/scripts/
COPY config.json /build/config.json

# Install OS Packages
RUN apt-get update && apt-get install -y \
    build-essential \
    curl wget \
    docker \
    dos2unix \
    git \
    tar zip unzip \
    less vim tree \
    jq \
    python3 python3-pip groff \
 && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10
RUN update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 10
RUN pip install --upgrade pip setuptools

RUN python3 -m pip install awscli --upgrade --no-cache-dir

# Install NodeJs
RUN curl -sL https://deb.nodesource.com/setup_8.x |  bash - \
    && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*

# Update Script permissions
RUN chmod -R u+rwx /build/scripts
RUN chmod u+s /build/
RUN chmod -R ugo+rx /opt/codeontap 

RUN /build/scripts/build_codeontap.sh
RUN /build/scripts/clone.sh

ENV AUTOMATION_BASE_DIR=/opt/codeontap/automation
ENV AUTOMATION_DIR=/opt/codeontap/automation/jenkins/aws
ENV GENERATION_BASE_DIR=/opt/codeontap/generation
ENV GENERATION_DIR=/opt/codeontap/generation/aws
ENV GENERATION_STARTUP_DIR=/opt/codeontap/startup

ENV REGION=""
ENV ACCOUNT=""
ENV PRODUCT=""
ENV ENVIRONMENT=""
ENV SEGMENT=""

WORKDIR /var/opt/codeontap