#!/bin/bash

# gen3 base
docker push "${DOCKER_REPO}:${DOCKER_TAG}" || exit $?
docker push "${DOCKER_REPO}:${DOCKER_TAG%-*}" || exit $?

# gen3 base - Jenkins JNLP
docker push "${DOCKER_REPO}:${DOCKER_TAG}-jenkins" || exit $?
docker push "${DOCKER_REPO}:${DOCKER_TAG%-*}-jenkins" || exit $?
docker push "${DOCKER_REPO}:${DOCKER_TAG}-jenkins-agent-jnlp" || exit $?

# gen3 builder 
docker push "${DOCKER_REPO}:${DOCKER_TAG}-builder" || exit $?
docker push "${DOCKER_REPO}:${DOCKER_TAG%-*}-builder" || exit $?

# gen3 builder - Jenkins JNLP
docker push "${DOCKER_REPO}:${DOCKER_TAG}-jenkins-builder" || exit $?
docker push "${DOCKER_REPO}:${DOCKER_TAG%-*}-jenkins-builder" || exit $?
docker push "${DOCKER_REPO}:${DOCKER_TAG}-jenkins-agent-jnlp-builder" || exit $?

# gen3 builder meteor
docker push "${DOCKER_REPO}:${DOCKER_TAG}-builder-meteor" || exit $?
docker push "${DOCKER_REPO}:${DOCKER_TAG%-*}-builder-meteor" || exit $?

# gen3 builder meteor - Jenkins JNLP
docker push "${DOCKER_REPO}:${DOCKER_TAG}-jenkins-builder-meteor" || exit $?
docker push "${DOCKER_REPO}:${DOCKER_TAG%-*}-jenkins-builder-meteor" || exit $?
docker push "${DOCKER_REPO}:${DOCKER_TAG}-jenkins-agent-jnlp-builder-meteor" || exit $?

# gen3 builder expo - Jenkins JNLP
docker push "${DOCKER_REPO}:${DOCKER_TAG}-jenkins-builder-expo" || exit $?
docker push "${DOCKER_REPO}:${DOCKER_TAG%-*}-jenkins-builder-expo" || exit $?
docker push "${DOCKER_REPO}:${DOCKER_TAG}-jenkins-agent-jnlp-builder-expo" || exit $?
