#!/bin/bash

# gen3 base
docker push "${DOCKER_REPO}:${DOCKER_TAG}" || exit $?
docker push "${DOCKER_REPO}:${DOCKER_TAG}-jenkins" || exit $?
docker push "${DOCKER_REPO}:${DOCKER_TAG}-jenkins-agent-jnlp" || exit $?

# gen3 builder 
docker push "${DOCKER_REPO}:${DOCKER_TAG}-builder" || exit $?
docker push "${DOCKER_REPO}:${DOCKER_TAG}-jenkins-builder" || exit $?
docker push "${DOCKER_REPO}:${DOCKER_TAG}-jenkins-agent-jnlp-builder" || exit $?